server:
  port: 8080

hubspot:
  client-id: sua_client_id
  client-secret: seu_client_secret
  redirect-uri: http://localhost:8080/oauth/callback
  scopes: contacts
  auth-url: https://app.hubspot.com/oauth/authorize
  token-url: https://api.hubapi.com/oauth/v1/token
  api-base-url: https://api.hubapi.com